#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py migrate

exec /usr/local/bin/gunicorn homedecor.wsgi --bind 0.0.0.0:1998 --chdir=/app
