version: "3.9"

services:
    es:
        image: elasticsearch:7.17.9
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        networks:
            - jobportal-app
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        ports:
            - "8000:8000"
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - es
        networks:
            - jobportal-app

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        volumes:
            - local_postgres_data:/var/lib/postgresql/data2
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - jobportal-app
    
    redis:
        image: redis:7-alpine
        networks:
            - jobportal-app

    celery_worker:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start-celeryworker
        volumes:
            - .:/app
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - redis
            - postgres
        networks:
            - jobportal-app

    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - jobportal-app

networks:
    jobportal-app:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    local_postgres_data: {}